import type { Metadata } from 'next'

import { Header } from '@src/components/Header'
import { pretendard } from '@src/styles/font'
import '@src/styles/globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="ko" className={pretendard.className}>
      <body className="bg-gray-100 pt-[100px] text-white">
        <Header />
        <div className="mx-auto w-full max-w-[1440px]">{children}</div>
      </body>
    </html>
  )
}
