import type { Metadata } from 'next'

import { Footer } from '@src/components/Footer'
import { Header } from '@src/components/Header'
import { pretendard } from '@src/styles/font'
import '@src/styles/globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="ko" className={pretendard.className}>
      <body className="bg-gray-100 text-white">
        <Header />
        <div className="bg-gray-100">{children}</div>
        <Footer />
      </body>
    </html>
  )
}
